export { default as IconClock } from './IconClock.vue'
export { default as IconPhone } from './IconPhone.vue'
export { default as IconLocation } from './IconLocation.vue'
export { default as IconFacebook } from './IconFacebook.vue'
export { default as IconInstagram } from './IconInstagram.vue'
export { default as IconYoutube } from './IconYoutube.vue'
export { default as IconWhatsapp } from './IconWhatsapp.vue'